AlignParameters:
  Enabled: false
ClassLength:
  CountComments: false
  Max: 200
LineLength:
  Max: 99
MethodLength:
  CountComments: false
  Max: 15
AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/**/*
    - config/**/*
    - !ruby/regexp /old_and_unused\.rb$/
